// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CurrentClient() {
  return window['go']['auth']['Service']['CurrentClient']();
}

export function DatabaseConfig() {
  return window['go']['auth']['Service']['DatabaseConfig']();
}

export function GetMasterKeyStorage() {
  return window['go']['auth']['Service']['GetMasterKeyStorage']();
}

export function GetSession() {
  return window['go']['auth']['Service']['GetSession']();
}

export function Login(arg1) {
  return window['go']['auth']['Service']['Login'](arg1);
}

export function Logout() {
  return window['go']['auth']['Service']['Logout']();
}

export function Register(arg1) {
  return window['go']['auth']['Service']['Register'](arg1);
}

export function RequireSession() {
  return window['go']['auth']['Service']['RequireSession']();
}

export function ResetPassword(arg1) {
  return window['go']['auth']['Service']['ResetPassword'](arg1);
}

export function SaveRecoveryKey(arg1, arg2) {
  return window['go']['auth']['Service']['SaveRecoveryKey'](arg1, arg2);
}

export function SetInactivityTimeout(arg1) {
  return window['go']['auth']['Service']['SetInactivityTimeout'](arg1);
}

export function SetMasterKeyStorage(arg1) {
  return window['go']['auth']['Service']['SetMasterKeyStorage'](arg1);
}

export function Startup(arg1) {
  return window['go']['auth']['Service']['Startup'](arg1);
}

export function TouchSession() {
  return window['go']['auth']['Service']['TouchSession']();
}

export function WithMasterKey(arg1) {
  return window['go']['auth']['Service']['WithMasterKey'](arg1);
}
