// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {auth} from '../models';

export function GetSession():Promise<auth.Session>;

export function Login(arg1:auth.LoginInput):Promise<boolean>;

export function Logout():Promise<void>;

export function Register(arg1:auth.RegisterInput):Promise<auth.User>;
