// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';
import {auth} from '../models';

export function CurrentClient():Promise<db.Client>;

export function DatabaseConfig():Promise<db.Config>;

export function GetMasterKeyStorage():Promise<string>;

export function GetSession():Promise<auth.Session>;

export function Login(arg1:auth.LoginInput):Promise<boolean>;

export function Logout():Promise<void>;

export function Register(arg1:auth.RegisterInput):Promise<auth.RegisterResult>;

export function RequireSession():Promise<auth.Session>;

export function ResetPassword(arg1:auth.ResetPasswordInput):Promise<auth.RegisterResult>;

export function SetMasterKeyStorage(arg1:string):Promise<string>;
