// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSession() {
  return window['go']['auth']['Service']['GetSession']();
}

export function Login(arg1) {
  return window['go']['auth']['Service']['Login'](arg1);
}

export function Logout() {
  return window['go']['auth']['Service']['Logout']();
}

export function Register(arg1) {
  return window['go']['auth']['Service']['Register'](arg1);
}

export function ResetPassword(arg1) {
  return window['go']['auth']['Service']['ResetPassword'](arg1);
}
