// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EnqueueDelete(arg1) {
  return window['go']['upload']['Service']['EnqueueDelete'](arg1);
}

export function EnqueueDownload(arg1) {
  return window['go']['upload']['Service']['EnqueueDownload'](arg1);
}

export function EnqueueFiles(arg1) {
  return window['go']['upload']['Service']['EnqueueFiles'](arg1);
}

export function FinalizeDownload(arg1) {
  return window['go']['upload']['Service']['FinalizeDownload'](arg1);
}

export function GetActiveTransfers() {
  return window['go']['upload']['Service']['GetActiveTransfers']();
}

export function GetStorageUsed() {
  return window['go']['upload']['Service']['GetStorageUsed']();
}

export function GetStoredFiles(arg1, arg2, arg3) {
  return window['go']['upload']['Service']['GetStoredFiles'](arg1, arg2, arg3);
}

export function PickFiles() {
  return window['go']['upload']['Service']['PickFiles']();
}

export function Startup(arg1) {
  return window['go']['upload']['Service']['Startup'](arg1);
}
