// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {upload} from '../models';
import {context} from '../models';

export function DeleteStoredFile(arg1:number):Promise<void>;

export function EnqueueDownload(arg1:number):Promise<upload.EnqueuedJob>;

export function EnqueueFiles(arg1:upload.EnqueueFilesInput):Promise<Array<upload.EnqueuedJob>>;

export function FinalizeDownload(arg1:number):Promise<string>;

export function GetActiveTransfers():Promise<Array<upload.EnqueuedJob>>;

export function GetStoredFiles():Promise<Array<upload.StoredFile>>;

export function PickFiles():Promise<Array<upload.PickedFile>>;

export function Startup(arg1:context.Context):Promise<void>;
