// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteFiles(arg1) {
  return window['go']['home']['Service']['DeleteFiles'](arg1);
}

export function DownloadFiles(arg1) {
  return window['go']['home']['Service']['DownloadFiles'](arg1);
}

export function GetFileDetails(arg1) {
  return window['go']['home']['Service']['GetFileDetails'](arg1);
}

export function GetHomeOverview() {
  return window['go']['home']['Service']['GetHomeOverview']();
}

export function GetStorageUsed() {
  return window['go']['home']['Service']['GetStorageUsed']();
}

export function GetStoredFiles(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['home']['Service']['GetStoredFiles'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateFile(arg1, arg2, arg3) {
  return window['go']['home']['Service']['UpdateFile'](arg1, arg2, arg3);
}
