// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {home} from '../models';

export function GetFileDetails(arg1:number):Promise<home.FileDetails>;

export function GetHomeOverview():Promise<home.HomeOverview>;

export function GetStoredFiles(arg1:string,arg2:number,arg3:number):Promise<home.StoredFilePage>;
