// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFileDetails(arg1) {
  return window['go']['home']['Service']['GetFileDetails'](arg1);
}

export function GetHomeOverview() {
  return window['go']['home']['Service']['GetHomeOverview']();
}

export function GetStoredFiles(arg1, arg2, arg3) {
  return window['go']['home']['Service']['GetStoredFiles'](arg1, arg2, arg3);
}
