// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {settings} from '../models';
import {context} from '../models';

export function GetDatabaseInfo():Promise<settings.DatabaseInfo>;

export function GetSettings():Promise<settings.Settings>;

export function PickFolder():Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateSettings(arg1:settings.UpdateSettingsInput):Promise<void>;
