// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {settings} from '../models';
import {context} from '../models';

export function GetSettings():Promise<settings.Settings>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateSettings(arg1:settings.Settings):Promise<void>;
